version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: brownie_prod_brownie
    container_name: brownie_point
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    command: /prodstart