# Generated by Django 3.0.11 on 2021-01-09 16:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('google_play_app_id', models.CharField(default=None, max_length=20, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('modified_on', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_form_id', models.CharField(max_length=20)),
                ('is_visited_by_cron', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('modified_on', models.DateField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_request.Company')),
            ],
            options={
                'db_table': 'interview_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('modified_on', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'job_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('modified_on', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeformWebhookData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_form_id', models.CharField(max_length=20)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('modified_on', models.DateField(default=django.utils.timezone.now)),
                ('interview_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_request.InterviewRequest')),
            ],
            options={
                'db_table': 'typeform_webhook_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InterviewRequestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_form_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('modified_on', models.DateField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_request.Company')),
                ('interview_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_request.InterviewRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_request.Users')),
            ],
            options={
                'db_table': 'interview_request_result',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_request.JobProfile'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_request.Users'),
        ),
    ]
