# Generated by Django 3.0.11 on 2021-01-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
