# Generated by Django 3.0.11 on 2021-01-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_request', '0003_auto_20210109_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
