# Generated by Django 3.0.11 on 2021-01-10 19:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_request', '0005_interviewrequestresult_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewrequestresult',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
